### ISSUE TITLE
Support a default IAM role when creating Lambda from zip

### ISSUE THREAD

**Issue by lindydonna** [pulumi/pulumi-aws-serverless#10]
If you point to a function for a route handler, the default roles for Lambda are configured automatically. If you're pointing to an external file and zipping it, you have to define all the default roles and policies. For example, see https://github.com/pulumi/pulumi-aws-serverless/blob/master/nodejs/aws-serverless/examples/api/index.ts#L20-L39

It would be nice to have an option to define all the roles by default.

**Comment by lukehoban** [comment]
Related to https://github.com/pulumi/pulumi-aws-serverless/issues/28.

**Comment by CyrusNajmabadi** [comment]
This is doable now, especially with the new apigateway API in aws-serverless.  Specifically, when you create routes, you are required to pass a ```Handler<Request, Response>```.  A ```Handler``` is satisfied with an aws.lambda.Function, and you can create an aws.lambda.function with ```serverless.createLambdaFunction(name, jsCallback, *opts*)```

these are opts are FunctionOptions and you can pass your own Role in there.
