### ISSUE TITLE
Add support for SQS event sources

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi-aws-serverless#16]
Lambda added support for SQS event sources today: https://aws.amazon.com/blogs/aws/aws-lambda-adds-amazon-simple-queue-service-to-supported-event-sources/.

We should add this to the `aws-serverless` library as an available event source.

**Comment by lukehoban** [comment]
See https://github.com/pulumi/pulumi-aws-serverless/pull/17.

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/pulumi/pulumi-aws-serverless/pull/17
