### ISSUE TITLE
InvalidParameterValueException: Maximum batch size must be between 1 and 10 inclusive

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi-aws-serverless#20]
If I do an SQS queue subscription with the default parameters, it fails with an error

`Error creating Lambda event source mapping: InvalidParameterValueException: Maximum batch size must be between 1 and 10 inclusive`

It seems I can fix this by passing an explicit `{ batchSize: 1 }`, but why not make that the default?

**Comment by lukehoban** [comment]
I believe this was fixed

**Comment by lukehoban** [comment]
I believe this was ultimately fixed in https://github.com/terraform-providers/terraform-provider-aws/pull/5024, but perhaps we never puled the latest from that PR back into our AWS provider fork?  /cc @CyrusNajmabadi.

**Comment by lukehoban** [comment]
I believe this will be fixed with https://github.com/pulumi/pulumi-aws/pull/264.

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/pulumi/pulumi-aws/pull/264
