### ISSUE TITLE
Consider more consistent naming

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi-aws-serverless#21]
I find the naming a little counter-intuitive for this package.

For instance, `queue` is a module with a `subscribe` function.  Yet our AWS package exports a `Queue` class, underneath an `sqs` module.

I've also been torn on the nerdy, yet consistent, naming of `subscribe`.

If I could choose, I'd mirror the modules and types as much as possible.  For example, rather than saying `serverless.queue.subscribe`, I think I'd prefer something like `serverless.sqs.onQueueMessage`.  Or, `serverless.sqs.Queue.onMessage`.

In the past, we had considered `sqsevents`, so that you can import them alongside one another easily

```
import {sqs} from "@pulumi/aws";
import {sqsevents} from "@pulumi/aws-serverless";

let q = new sqs.Queue(...);
sqsevents.onQueueMessage(q, ...);
```

I think taking a step back and looking at how the package will be used alongside other packages would be a good exercise to perform if and when we consider renaming things.

I'm filing this "as a user", just some API usability feedback from me.  If there is something already tracking this, please dupe, or if you're truly happy with our current approach, feel free to close. 

If we're going to change, however, let's decide soon before lots of code gets written atop this amazing library :smile:

**Comment by lukehoban** [comment]
> For instance, queue is a module with a subscribe function. Yet our AWS package exports a Queue class, underneath an sqs module.

Agreed, this was inconsistent with our previous decision in this repo to parent everything under the same modules as the AWS package.

> I've also been torn on the nerdy, yet consistent, naming of subscribe.

Yes - in our last discussion on this, we did not arrive at any sufficiently consistent approach to naming.  Now that we have a half dozen APIs here, we should review and apply a consistent approach to these names.

**Comment by CyrusNajmabadi** [comment]
> If I could choose, I'd mirror the modules and types as much as possible. For example, rather than saying serverless.queue.subscribe, I think I'd prefer something like serverless.sqs.onQueueMessage. Or, serverless.sqs.Queue.onMessage.

I'm ok with this.  It seemed nicer to me to be able to say "serverless.queue.whatever" since these were the operations that were effectively going to take queues.  So, similar to extension methods, the primary arg they operated on becomes the name of the thing on the left.

However, i agree that this isn't necessarily as well thought out or consistent as just using the same naming from aws.  So i'm ok with changing.  What do we feel is acceptable from a breaking change perspective?

**Comment by lukehoban** [comment]
PR at https://github.com/pulumi/pulumi-aws-serverless/pull/31 is tracking work on this, but we're going to do another review pass on the overall architecture here before we land the broad breaking changes here.

**Comment by CyrusNajmabadi** [comment]
This is being done as part of the work to collapse aws-serverless into aws, and azure-serverless into azure.  However, the goal is not 'consistency' across clouds.  The goal is to be consistent with the general terminology of each specific cloud provider.

**Comment by CyrusNajmabadi** [comment]
Closing as this work has generally be done.  We can address any future work with individual targeted issues
