### ISSUE TITLE
Allow easy way to create `Function` from a callback with other parameters overriden

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi-aws-serverless#28]
We have a `createFunction` helper, which is close to this - but we should design the API intentionally and make sure it layers on the APIs in `aws.serverless.Function` in a nice way.

This would be a way to create an `aws.lambda.Function` object from a callback, but with control over all of the parameters of the Lambda Function if desired.

**Comment by CyrusNajmabadi** [comment]
@lukehoban I'm not sure i understand this work item.  If you want to make a Function from a callback, with some parameters overridden, it's actually pretty simple.  All you do is call:

```ts
new aws.serverless.Function(name, funcOptions, func);
```

Is there a reason this is not sufficient?

**Comment by lukehoban** [comment]
Good point - closing this out.
