### ISSUE TITLE
Need to expose publish field on serverlessFunctionOptions

### ISSUE THREAD

**Issue by chrsmith** [pulumi/pulumi-aws-serverless#9]
`aws.serverless.FunctionOptions` doesn't contain a `publish` field, whereas `aws.lambda.FunctionArgs` does. It appears that we either need to default to setting this to `true` in the `aws.serverless.Function`'s constructor.

Not 100% sure how/when this is required, the docs just describe it as:
> Whether to publish creation/change as new Lambda Function Version. Defaults to `false`.

However, in order to attach it to a CloudFront event (lambda@edge?) it seems required.

```
Diagnostics:
  aws:cloudfront:Distribution: cdn
    error: Plan apply failed: updating urn:pulumi:www.pulumi.com-chris::www.pulumi.com::aws:cloudfront/distribution:Distribution::cdn: InvalidLambdaFunctionAssociation: The function ARN must reference a specific function version. (The ARN must end with the version number.) ARN: arn:aws:lambda:us-west-2:153052954103:function:urlRewriter-64c1935:$LATEST
```

Perhaps we don't need to expose the `publish` field on `serverless.FunctionOptions`, since it may be only required in certain cases. Would it make more sense to pass an optional `aws.lambda.FunctionArgs` to merge into the lambda we generate inside the serverless package?

**Comment by joeduffy** [comment]
I'm closing this out, as I believe the way we now support functions at the `@pulumi/aws` layer means you can get the full power of any lambda options available. @CyrusNajmabadi @chrsmith Please reopen if I'm mistaken.
